/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Tue Oct 25 2016 10:24:40 GMT+0300 (EAT)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {
    APP_URL: 'http://localhost',
    API_PROTOCOL: 'http',
    API_DOMAIN: 'localhost:8000',
    API_baseUrl: '/api/',
    API_apiVersion: '1',
    UPLOADS_URL: 'http://localhost:8000/static/uploads/',
    DEFAULT_PRODUCT_IMAGE: 'http://localhost:3000/assets/images/ng2.jpg',
};
//# sourceMappingURL=env.js.map